Algoritmo "aumento"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcio Elias Silva Marques
// Data atual  : 15/10/2021
Var
   salario, aumento, calculo: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Informe o salário")
leia(salario)
calculo <- salario * 0.3
aumento <- salario + calculo
escreval("O salário mais o aumento de 30% fica ", aumento)

Fimalgoritmo